name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Makefile
      run: ./configure

    - name: Run make to create executable
      run: make
      run: echo "🍏 The make status is ${{ job.status }}."

    - name: Run make check to see output of executable
      run: make check
      run: echo "🍏 The make check status is ${{ job.status }}."
